services:
  backend:
    build: .
    container_name: futbol-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # ❌ ERROR 5 (RED INTERNA): Apunta a localhost dentro de la red del contenedor. 
      # Deben cambiarlo a postgresql://postgres:password123@db_futbol:5432/futbol_db
      - DATABASE_URL=postgresql://postgres:password123@localhost:5432/futbol_db 
    depends_on:
      - db_futbol

  db_futbol:
    image: postgres:15-alpine
    container_name: futbol-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: futbol_db
    ports:
      - "5432:5432"
    volumes:
      # ❌ ERROR 6 (VOLÚMENES): Mapeo incorrecto de la ruta interna de Postgres. 
      # Pusieron /data/db (que es de MongoDB). Postgres arrojará un error de inicialización en los logs 
      # porque espera la ruta /var/lib/postgresql/data.
      - postgres_data:/data/db

volumes:
  postgres_data: